"""
OCP transcription using CasADi's Opti API — v3.

Each micro-sector OCP minimises sector traversal time over a fixed spatial
domain [0, L_straight], priced against Energy Store consumption, subject to
longitudinal point-mass dynamics and the 2026 regulatory envelope.

    * Longitudinal point-mass dynamics            (dynamics.py v3)
    * Initial / terminal velocity                 v(0)=v_exit, v(L)=v_entry_target
    * Initial store energy                        E(0) = E_initial
    * Store energy bounds                         0 <= E <= e_batt_capacity
    * Cumulative Recharge                         E_har(0) = 0, monotone
    * ERS-K absolute DC power, both directions    C5.2.7
    * ERS-K deployment speed envelope             C5.2.8(ii)
    * ICE power limit and one-sided force         0 <= F_ice*v <= p_ice_max
    * Longitudinal friction circle                aero-coupled normal load
    * Aero variable a in [0, 1]                   relaxed-binary X/Z mode

v3 CHANGES (supersede v2)
=========================

A. CORRECTED DEPLOYMENT ENVELOPE.  v2 implemented a single ramp holding
   350 kW to 290 kph and tapering to zero at 355 kph. That curve appears
   nowhere in the regulations: it takes the 290 kph knee from C5.2.8(i)
   and the 355 kph zero from C5.2.8(ii).

   The correct envelope for a QUALIFYING lap is C5.2.8(ii). Qualifying is
   a Lap Time Classified Session (Section B, Appendix B1); Overtake is
   enabled prior to any LTCS (B7.2.2a) and activated at all times whilst
   enabled during one (B7.2.3b.i). C5.2.8(i) is the curve that applies in
   a Race or Sprint when Overtake is NOT active, and is not applicable
   here. The v2 comment at VehicleParams VP-22 asserting the opposite is
   withdrawn.

   Impact measured on the v3 label set: 27.9% of the 11,434 sector
   instances exceed 290 kph and therefore carried a mis-specified
   deployment bound, with errors up to -256 kW at 337.5 kph. Only 1.06%
   exceed 337.5 kph, so under the corrected envelope the C5.2.7 flat cap
   is the binding constraint for ~99% of the dataset and the speed taper
   is close to inactive. Variation in the P_deploy label is consequently
   generated by the energy price lambda and by the friction circle at
   corner exit, not by the taper.

B. SMOOTH CLAMP ON THE ENVELOPE.  The C5.2.8(ii) taper line goes negative
   above 355 kph. In v2, with a single signed control, that merely forced
   a small harvest — conservative and documented. With the v3 split
   (F_dep >= 0) a negative upper bound on F_dep*v is INFEASIBLE, so the
   solve fails rather than degrading.

   The exact admissible set {0 <= P <= max(0, c - b*v)} is non-convex, so
   no exact linear-inequality representation exists. The taper is
   therefore clamped smoothly:

       P_env(v) = 0.5 * (X + sqrt(X^2 + delta^2)),   X = c - b*v

   which is C-infinity, has no active-set behaviour, and approximates
   max(0, X) to within delta/2. The approximation is PERMISSIVE by at
   most delta/2, so with the default delta = 5 kW the envelope is
   overstated by at most 2.5 kW near the zero — against a 350 kW cap,
   negligible. One instance in 11,434 currently reaches 355 kph; expect
   that population to grow modestly on re-solve, since correcting (A)
   lets the cars accelerate harder through 290-337.5 kph.

C. HARVEST STATE.  Third state E_har carries cumulative Recharge at the
   CU-K HV DC bus (C5.2.10). Unconstrained at sector level — the 8.5 MJ
   cap is a lap-level quantity applied in the Phase 4 outer loop — but it
   must be produced here because it cannot be recovered from net energy
   after the fact.

D. ENERGY PRICE (lambda) REPLACES THE TIE-BREAK WEIGHT.  v2 carried
   -epsilon*E[N] as a tie-break, calibrated small enough to reproduce the
   epsilon -> 0 limit. The Phase 4 co-state formulation prices net store
   consumption at lambda:

       min  t_sector + lambda * (E[0] - E[N])

   and since E[0] is fixed by the boundary condition this is -lambda*E[N]
   plus a constant. The v2 tie-break and the v3 co-state are therefore the
   SAME TERM: epsilon is simply lambda at the bottom of its range. What
   changes is interpretation and use — lambda is swept over a grid and
   logged as both a label column and a surrogate feature, so that the
   Phase 4 outer loop can bisect it to meet a lap-level energy target.

   The v2 justification (bounded tie-break, matches epsilon -> 0) holds
   only at the bottom of the grid and must NOT be carried into the methods
   chapter unamended. Above that, lambda is a genuine shadow price and the
   labels are deliberately lambda-dependent.

   lambda must be STRICTLY POSITIVE. At lambda = 0 terminal store energy
   is unpriced and the (F_dep, F_reg) simultaneity described in
   dynamics.py becomes a free degeneracy. Set the bottom of the grid to
   the calibrated v2 epsilon rather than to zero.

E. OPTIONAL HARVEST PRICE (mu).  If the lap-level Recharge cap binds under
   single-price bisection, a second multiplier on cumulative harvest is
   required. The hook is provided (+mu*E_har[N], default mu = 0) so that
   the two-price extension is a call-site change rather than a rebuild.
   Check whether the cap actually binds on a qualifying lap before
   building the 2-D outer solve.

Transcription: direct trapezoidal collocation with N intervals over s.
States v, E, E_har discretised at N+1 knots; controls F_ice, F_dep, F_reg,
F_brake, a piecewise constant on each interval (zero-order hold). Standard
direct collocation (Kelly, 2017).

CALL-SITE CHANGES REQUIRED
==========================

solver.py
    * OCPHandle no longer exposes F_mguk as a decision variable. Warm-start
      must set F_dep and F_reg instead of F_mguk. The derived expression
      handle.F_mguk_expr is provided for extraction/plotting only —
      opti.set_initial() on it will fail.
    * OCPResult should carry E_har_traj and the terminal harvest E_har[N];
      Phase 4 lap assembly needs both.
    * Label extraction reading F_mguk_traj should switch to
      F_dep_traj - F_reg_traj, or use F_mguk_expr at solve time.

batch.py
    * Rename the keyword terminal_energy_weight -> energy_price at every
      call site. Passing the old name now raises TypeError by design.
    * Add the lambda grid as a loop nested inside the SoC loop, reusing the
      existing warm-start chain pattern with its cold-start fallback.
      Sweep lambda ascending and warm-start each solve from the previous
      lambda at the same SoC: the parameter step is small and IPOPT
      converges in a fraction of the cold-start iterations.
    * Persist energy_price and terminal E_har as label columns.

vehicle.py
    * v_env_full / v_env_zero (VP-21/VP-22) are superseded and unused.
      Remove them or mark deprecated; leaving them invites reuse.
    * VP-13 comment: the "9 MJ Monaco/Hungary" figure has no basis in
      C5.2.10, which caps at 8.5 MJ, reducible to 7 MJ and to no less
      than 5 MJ for Qualifying.
    * VP-14 comment: 4 MJ is a max-minus-min excursion limit whilst on
      track (C5.2.9), not a storage capacity.
    * VP-12 comment: the 250 kW figure is C5.2.8(iii), which applies only
      in Race or Sprint on specified sectors during a power-limited
      period. Not applicable to qualifying.
"""

from __future__ import annotations

from dataclasses import dataclass

import casadi as ca

from f1_pipeline.ocp import regs_2026
from f1_pipeline.ocp.dynamics import (
    lift_force,
    p_deploy_dc,
    p_regen_dc,
    state_derivatives,
)
from f1_pipeline.ocp.vehicle import VehicleParams

# ----------------------------------------------------------------------
# Regulatory envelope constants — FIA 2026 Section C, Issue 20, C5.2.8(ii)
#
#   Regulation form (v in kph, P in kW):  P = 7100 - 20*v,  v < 355
#   SI form         (v in m/s, P in W):   P = 7.10e6 - 7.20e4*v
#
# Mirrors regs_2026.py. The self-check at the foot of this module
# cross-validates against it when importable, so the two cannot drift.
# ----------------------------------------------------------------------
ENV_OT_INTERCEPT = 7.10e6  # W
ENV_OT_SLOPE = 7.20e4  # W per (m/s)
ENV_CLAMP_DELTA_DEFAULT = 5.0e3  # W, smoothing width of the max(0, .) clamp


def _envelope_dc_watts(v, delta: float):
    """
    C5.2.8(ii) deployment envelope, smoothly clamped at zero.

    Returns a CasADi expression (or float) giving the maximum permitted
    electrical DC deployment power at speed v. The C5.2.7 absolute cap is
    imposed separately as its own constraint rather than folded in here,
    so that the two limits remain individually identifiable in the dual
    variables.
    """
    X = ENV_OT_INTERCEPT - ENV_OT_SLOPE * v
    return 0.5 * (X + ca.sqrt(X * X + delta * delta))


# ----------------------------------------------------------------------
# Sector input container
# ----------------------------------------------------------------------
@dataclass(frozen=True)
class SectorInputs:
    """Per-micro-sector OCP inputs read from the Phase 1 feature matrix."""

    v_exit: float  # corner-exit velocity (m/s)
    v_entry_target: float  # next-corner entry target velocity (m/s)
    L_straight: float  # straight length (m)
    E_initial: float  # initial store energy at sector start (J)
    sector_id: str = ""  # optional row identifier for logging


# ----------------------------------------------------------------------
# Bundle returned to the solver layer
# ----------------------------------------------------------------------
@dataclass
class OCPHandle:
    """Container exposing the Opti instance plus its decision variables."""

    opti: ca.Opti
    v: ca.MX
    E: ca.MX
    E_har: ca.MX
    F_ice: ca.MX
    F_dep: ca.MX
    F_reg: ca.MX
    F_brake: ca.MX
    a: ca.MX
    F_mguk_expr: ca.MX  # derived: F_dep - F_reg. Extraction only —
    # opti.set_initial() on this will fail.
    N: int
    L: float
    inputs: SectorInputs
    params: VehicleParams
    energy_price: float  # lambda (s/J), logged as label + feature
    harvest_price: float  # mu (s/J), 0 unless the Recharge cap binds


# ----------------------------------------------------------------------
# Builder
# ----------------------------------------------------------------------
def build_ocp(
    inputs: SectorInputs,
    params: VehicleParams,
    N: int = 50,
    aero_regularisation_weight: float = 1e-3,
    force_aero_shut: bool = False,
    *,
    energy_price: float,
    harvest_price: float = 0.0,
    envelope_clamp_delta: float = ENV_CLAMP_DELTA_DEFAULT,
    **_deprecated,
) -> OCPHandle:
    """
    Build the CasADi Opti problem for one (micro-sector, SoC, lambda) scenario.

    Parameters
    ----------
    inputs : SectorInputs
        Geometric / kinematic / energetic inputs defining the scenario.
    params : VehicleParams
        Vehicle parameter set (see vehicle.py).
    N : int
        Number of collocation intervals. 50 is reasonable for straight
        micro-sectors of 200-1500 m. The v3 formulation adds one state and
        one control relative to v2, so expect a per-solve cost increase;
        measure it in the smoke test before sizing the lambda grid.
    aero_regularisation_weight : float
        Cost weight on the discrete derivative of a(s). Penalises
        oscillation and encourages a single clean switch.
    force_aero_shut : bool
        Zone-ineligibility flag. When True the aero variable's upper bound
        collapses to 0 (car held in Z-mode throughout). With equal lower
        and upper bounds IPOPT's fixed-variable treatment eliminates a(s)
        from the KKT system.
    energy_price : float  (REQUIRED, keyword-only)
        lambda, the price on net Energy Store consumption (s/J). Must be
        strictly positive — see module docstring section D. No default is
        provided deliberately: the value comes from the sweep grid, and an
        unset price must never be used silently.
    harvest_price : float
        mu, the price on cumulative Recharge (s/J). Leave at 0 unless the
        lap-level Recharge cap binds under single-price bisection.
    envelope_clamp_delta : float
        delta, the smoothing width of the max(0, .) clamp on the C5.2.8(ii)
        taper (W). Permissive by at most delta/2 near the envelope zero.

    Returns
    -------
    OCPHandle
        Configured but unsolved Opti instance plus references to all
        decision variables for downstream extraction.

    Raises
    ------
    TypeError
        If the withdrawn v2 keyword terminal_energy_weight is passed. The
        term survives with identical algebra but different semantics, so
        silent aliasing would let v2 call sites run with v3 intent.
    ValueError
        If energy_price is not strictly positive.
    """
    if "terminal_energy_weight" in _deprecated:
        raise TypeError(
            "terminal_energy_weight was renamed to energy_price in v3. "
            "The algebra is unchanged (-lambda*E[N]) but the semantics are "
            "not: it is now a swept co-state, not a calibrated tie-break. "
            "Update the call site rather than aliasing."
        )
    if _deprecated:
        raise TypeError(f"Unexpected keyword arguments: {sorted(_deprecated)}")
    if not energy_price > 0.0:
        raise ValueError(
            f"energy_price must be strictly positive, got {energy_price}. "
            "At lambda = 0 terminal store energy is unpriced and the "
            "(F_dep, F_reg) simultaneity becomes a free degeneracy. Set the "
            "bottom of the sweep grid to the calibrated v2 epsilon."
        )

    opti = ca.Opti()
    L = inputs.L_straight
    h = L / N  # spatial step

    # ------------------------------------------------------------------
    # Decision variables
    # ------------------------------------------------------------------
    v = opti.variable(N + 1)  # velocity at knots
    E = opti.variable(N + 1)  # store energy at knots
    E_har = opti.variable(N + 1)  # cumulative Recharge at knots
    F_ice = opti.variable(N)  # ICE force, ZOH per interval
    F_dep = opti.variable(N)  # MGU-K deployment force, ZOH, >= 0
    F_reg = opti.variable(N)  # MGU-K regen force, ZOH, >= 0
    F_brake = opti.variable(N)  # friction-brake force, ZOH, >= 0
    a = opti.variable(N)  # aero mode, ZOH per interval

    # ------------------------------------------------------------------
    # Bounds
    # ------------------------------------------------------------------
    # Velocity: floor avoids the 1/v singularity in the cost; ceiling is
    # well above any attainable speed (110 m/s = 396 kph).
    opti.subject_to(opti.bounded(5.0, v, 110.0))

    # Store energy. Article C5.2.9 limits the max-minus-min EXCURSION of
    # the state of charge to 4 MJ whilst the car is on track — it is not a
    # capacity. Within a single micro-sector with E(0) pinned, bounding E
    # to [0, 4 MJ] is a defensible proxy for that excursion limit. At lap
    # level in Phase 4 the correct statement is
    #     max_s E(s) - min_s E(s) <= 4 MJ
    # and must be enforced there, not inherited from this bound.
    opti.subject_to(opti.bounded(0.0, E, params.e_batt_capacity))

    # Cumulative Recharge: non-negative, unbounded above at sector level.
    # The 8.5 MJ cap of C5.2.10 is a per-LAP quantity (reducible to 7 MJ
    # under (i), and to no less than 5 MJ for Qualifying under (ii)) and is
    # applied in the Phase 4 outer loop, not here.
    opti.subject_to(E_har >= 0.0)

    opti.subject_to(F_ice >= 0.0)  # engine cannot brake in this model
    opti.subject_to(F_dep >= 0.0)  # deployment is one-sided by construction
    opti.subject_to(F_reg >= 0.0)  # regen is one-sided by construction
    opti.subject_to(F_brake >= 0.0)  # friction brake cannot accelerate

    a_ub = 0.0 if force_aero_shut else 1.0
    opti.subject_to(opti.bounded(0.0, a, a_ub))

    # ------------------------------------------------------------------
    # Boundary conditions
    # ------------------------------------------------------------------
    opti.subject_to(v[0] == inputs.v_exit)
    opti.subject_to(v[N] == inputs.v_entry_target)
    opti.subject_to(E[0] == inputs.E_initial)
    opti.subject_to(E_har[0] == 0.0)

    # Aero mode starts at Z (a=0). At sector start (corner apex) the car has
    # just exited a corner and is in high-downforce Z-mode for lateral grip.
    # The longitudinal-only OCP has no native incentive to represent this
    # (the apex's lateral-grip requirement is unmodelled — proposal §5.2), so
    # it is imposed phenomenologically. Without it the OCP picks X-mode at
    # s=0 universally, collapsing d_X to ~0 and making the aero-switch label
    # meaningless for surrogate training. Redundant under force_aero_shut but
    # retained so the constraint set stays structurally identical.
    opti.subject_to(a[0] == 0.0)

    # ------------------------------------------------------------------
    # Dynamics — trapezoidal collocation
    #   x_{k+1} = x_k + (h/2) * (f(x_k, u_k) + f(x_{k+1}, u_k))
    # Controls are piecewise constant within the interval (zero-order hold).
    # ------------------------------------------------------------------
    for k in range(N):
        dv0, dE0, dH0 = state_derivatives(
            v[k], F_ice[k], F_dep[k], F_reg[k], F_brake[k], a[k], params
        )
        dv1, dE1, dH1 = state_derivatives(
            v[k + 1], F_ice[k], F_dep[k], F_reg[k], F_brake[k], a[k], params
        )
        opti.subject_to(v[k + 1] == v[k] + 0.5 * h * (dv0 + dv1))
        opti.subject_to(E[k + 1] == E[k] + 0.5 * h * (dE0 + dE1))
        opti.subject_to(E_har[k + 1] == E_har[k] + 0.5 * h * (dH0 + dH1))

        # Mid-interval velocity as the ZOH proxy for power constraints.
        v_mid = 0.5 * (v[k] + v[k + 1])

        # --- ERS-K electrical limits ----------------------------------
        # Both C5.2.7 and C5.2.8 constrain electrical DC power, not wheel
        # power. v2 compared wheel power against the caps, which was ~5%
        # permissive on the deployment side.
        P_dep = p_deploy_dc(F_dep[k], v_mid, params)
        P_reg = p_regen_dc(F_reg[k], v_mid, params)

        # C5.2.7 — absolute limit, both directions. Stated as an absolute
        # limit, so it binds harvest as well as deployment. The C5.2.8
        # speed taper governs power "used to propel the car" ONLY and does
        # not apply to Recharge: harvest is capped flat at 350 kW at all
        # speeds. This asymmetry is deliberate and belongs in the methods
        # chapter — it means a high-speed braking zone can harvest at full
        # rate where deployment would already be tapered toward zero.
        opti.subject_to(P_dep <= params.p_mguk_max)
        opti.subject_to(P_reg <= params.p_regen_max)

        # C5.2.8(ii) — qualifying deployment envelope, smoothly clamped.
        opti.subject_to(P_dep <= _envelope_dc_watts(v_mid, envelope_clamp_delta))

        # ICE power envelope (wheel-equivalent, per the v2 convention).
        opti.subject_to(F_ice[k] * v_mid <= params.p_ice_max)

        # --- Longitudinal friction circle -----------------------------
        # All tractive and braking forces pass through the tyre contact
        # patch, so all four actuator forces enter the limit. Drag is a
        # resistance, not an actuator force, so it does not.
        #
        # Maximum tyre force is mu*N with N = m*g - F_lift (F_lift signed,
        # negative for downforce). Downforce therefore raises the
        # longitudinal traction ceiling — the mechanism by which Z-mode
        # permits full deployment at low corner-exit speeds where X-mode
        # would clip it. This couples a(s) into the friction circle and is
        # what makes d_X a physically meaningful label. With the C5.2.8
        # taper now near-inactive across ~99% of the dataset, this coupling
        # and the energy price lambda are the two remaining generators of
        # variation in the P_deploy target.
        F_lift_k = lift_force(v_mid, a[k], params)
        N_normal = params.mass_total * params.g - F_lift_k
        F_long = F_ice[k] + F_dep[k] - F_reg[k] - F_brake[k]
        f_max = params.mu_long * N_normal
        opti.subject_to(opti.bounded(-f_max, F_long, f_max))

    # ------------------------------------------------------------------
    # Cost
    #   sector time  +  aero regularisation
    #                -  lambda * E[N]        (net store consumption)
    #                +  mu * E_har[N]        (cumulative Recharge, optional)
    # ------------------------------------------------------------------
    # Integral of (1/v) ds, trapezoidal — proposal Eq. 1.
    t_sector = 0
    for k in range(N):
        t_sector += 0.5 * h * (1.0 / v[k] + 1.0 / v[k + 1])

    # Penalise oscillation in the aero variable (proposal TR-1 mitigation).
    aero_smoothness = 0
    for k in range(N - 1):
        d_a = a[k + 1] - a[k]
        aero_smoothness += d_a * d_a

    # lambda*(E[0] - E[N]) differs from -lambda*E[N] by a constant, since
    # E[0] is pinned by the boundary condition. The constant is dropped.
    objective = (
        t_sector + aero_regularisation_weight * aero_smoothness - energy_price * E[N]
    )
    if harvest_price != 0.0:
        objective = objective + harvest_price * E_har[N]

    opti.minimize(objective)

    # ------------------------------------------------------------------
    # Initial guess
    #
    # Linear v(s) between the boundary conditions. An earlier tent profile
    # (peak mid-sector) violated the friction circle on deceleration-
    # dominant sectors where v_entry_target << v_exit, because the implied
    # terminal deceleration exceeded mu*g. A monotonic ramp is safe for
    # both regimes: IPOPT discovers the true optimum (which usually does
    # peak slightly) but never starts outside the feasible region.
    # ------------------------------------------------------------------
    accelerating = inputs.v_entry_target >= inputs.v_exit

    for k in range(N + 1):
        frac = k / N
        v_guess = inputs.v_exit + frac * (inputs.v_entry_target - inputs.v_exit)
        opti.set_initial(v[k], v_guess)
        # Gradual store depletion on acceleration-dominant sectors,
        # gradual accumulation on deceleration-dominant ones.
        if accelerating:
            opti.set_initial(E[k], inputs.E_initial * (1.0 - 0.3 * frac))
        else:
            opti.set_initial(
                E[k],
                min(inputs.E_initial * (1.0 + 0.3 * frac), params.e_batt_capacity),
            )
        opti.set_initial(E_har[k], 0.0)

    for k in range(N):
        opti.set_initial(F_ice[k], 5000.0)
        # One-sided guesses matching the expected regime. Seeding the
        # inactive side at exactly zero sits on its bound, which IPOPT's
        # interior-point method dislikes; a small positive value keeps the
        # iterate strictly interior.
        if accelerating:
            opti.set_initial(F_dep[k], 1000.0)
            opti.set_initial(F_reg[k], 1.0)
        else:
            opti.set_initial(F_dep[k], 1.0)
            opti.set_initial(F_reg[k], 1000.0)
        # Friction brake starts near zero — the solver brings it in only
        # when regen is constrained (store cap, power limit, friction
        # circle).
        opti.set_initial(F_brake[k], 1.0)
        # Aero guess: nominal X-mode mid-sector; under force_aero_shut the
        # guess must respect the collapsed bound.
        if force_aero_shut:
            opti.set_initial(a[k], 0.0)
        else:
            opti.set_initial(a[k], 1.0 if 0.2 < k / N < 0.7 else 0.0)

    return OCPHandle(
        opti=opti,
        v=v,
        E=E,
        E_har=E_har,
        F_ice=F_ice,
        F_dep=F_dep,
        F_reg=F_reg,
        F_brake=F_brake,
        a=a,
        F_mguk_expr=F_dep - F_reg,
        N=N,
        L=L,
        inputs=inputs,
        params=params,
        energy_price=energy_price,
        harvest_price=harvest_price,
    )


# ----------------------------------------------------------------------
# Self-check — run `python problem.py`
# ----------------------------------------------------------------------
if __name__ == "__main__":
    delta = ENV_CLAMP_DELTA_DEFAULT

    def env(v_ms):
        return float(_envelope_dc_watts(ca.DM(v_ms), delta))

    # Knee: 350 kW at 337.5 kph (93.75 m/s).
    assert abs(env(93.75) - 350e3) < delta, env(93.75)
    # Zero: clamp yields delta/2 at the envelope zero, 355 kph.
    assert abs(env(98.6111) - delta / 2.0) < 1.0, env(98.6111)
    # Beyond the zero the clamp decays to ~0 and never goes negative.
    assert env(105.0) >= 0.0
    assert env(105.0) < 100.0, env(105.0)
    # Monotone decreasing in v.
    assert env(80.0) > env(93.75) > env(98.0) > env(105.0)
    # Permissive by at most delta/2 everywhere.
    for v_ms in (60.0, 80.0, 93.75, 96.0, 98.6111, 101.0):
        X = ENV_OT_INTERCEPT - ENV_OT_SLOPE * v_ms
        assert env(v_ms) - max(0.0, X) <= delta / 2.0 + 1e-6

    # Cross-validate against regs_2026.py where importable, so the two
    # copies of C5.2.8(ii) cannot drift apart.
    try:
        import regs_2026

        for v_ms in (60.0, 85.0, 93.75, 96.0):
            reg = regs_2026.p_deploy_max(v_ms, overtake=True)
            here = min(350e3, env(v_ms))
            assert abs(reg - here) < delta, (v_ms, reg, here)
        print("  cross-validated against regs_2026.py")
    except ImportError:
        print("  regs_2026.py not importable — cross-validation skipped")

    print("problem.py v3 envelope self-check passed")
    print("  C5.2.8(ii): 350 kW to 337.5 kph, zero at 355.0 kph")
    print(
        f"  clamp delta = {delta / 1e3:.1f} kW (permissive by <= {delta / 2e3:.2f} kW)"
    )
    for kph in (250, 290, 320, 337.5, 345, 355, 360):
        p = min(350e3, env(kph / 3.6))
        print(f"    {kph:6.1f} kph -> {p / 1e3:6.1f} kW")
